"""expand projects for workspace

Revision ID: 417850269032
Revises: 013c04b7c398
Create Date: 2026-08-03 09:39:29.271202
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "417850269032"
down_revision: str | Sequence[str] | None = "013c04b7c398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure existing orphan projects are deleted before adding NOT NULL constraints
    op.execute("DELETE FROM projects")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workspace_id", sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column("name", sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column("description", sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_projects_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_projects_workspace_id_workspaces"),
            "workspaces",
            ["workspace_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_projects_workspace_id_workspaces"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_projects_workspace_id"))
        batch_op.drop_column("status")
        batch_op.drop_column("description")
        batch_op.drop_column("name")
        batch_op.drop_column("workspace_id")
    # ### end Alembic commands ###
